### ISSUE TITLE
not able to connect from browser

### ISSUE THREAD

**Issue by arawak** [cloudamqp/websocket-tcp-relay#1]
I thought I'd give this a try locally, to see if I can access backend services over AMQP from a browser. However, I'm not able to get anywhere using the [sample code from the amqp-client.js repo](https://github.com/cloudamqp/amqp-client.js)

I have RabbitMQ 3.8.9 running locally on my dev machine, which is running Ubuntu 22.10 (impish). I'm trying to run the websocket proxy locally so that I can run the sample code in VSC's live server and then assess suitability for use in building a JS library that uses AMQP instead of REST web services. 

The installation instructions don't work for me, as they assume very specific versions of Ubuntu. Working around this, I still cannot install due to missing dependencies:

```
The following packages have unmet dependencies:
websocket-tcp-relay : Depends: libgc1c2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

So, moving on to docker, using the IP of my workstation (which I verified works with amqpcat)...

```
docker run --rm -it -p 15670:15670 cloudamqp/websocket-tcp-relay --upstream tcp://192.168.26.30:5672
```

...I get:

```
Listening: http://127.0.0.1:15670
Upstream: tcp://192.168.26.30:5672
PROXY protocol: disabled
Web root: Not found
```
...which seems fine.

However, when I run the sample HTML it does not connect. Stepping through the JS, I can see that it blocks on

```
const conn = await amqp.connect()
```

Am I doing something wrong?

**Comment by carlhoerberg** [comment]
ah, thank you for reporting the libgc1c2 problem, should be fixed now. But anyway, regarding the connect, I wonder if it might be a security thing in the browser that prevents plain text (non TLS) connections? they're adding more and more of that stuff... Or if there's a local firewall that somehow blocks localhost traffic? i assume that the browser and docker runs on the same host?

**Comment by carlhoerberg** [comment]
what does the connecting js code look like?

**Comment by arawak** [comment]
The client code almost verbatim from the "Using AMQP over WebSockets in a browser" [sample on the amqp-client.js repo](https://github.com/cloudamqp/amqp-client.js). I grabbed amqp-websocket-client.mjs from there as well. My only changes are to use a non-guest user (tested with amqpcat) and change the import to be in the same directory.

There's no firewall... rabbitmq is installed via apt, and the proxy is running on docker, and the page is served from VCS's liveserver. Everything running on localhost.

Browser security is an interesting thought... I'll try it with a couple different browsers. Chrome had nothing in the console log though. I'd think they'd log if they were applying a security policy. 

I'll also see if I can learn enough ruby to add/enable some logging in the proxy. My gut feeling is that it's blocking in there some time right after connect.

**Comment by jonaskello** [comment]
@arawak I'm also trying to make it connect but no luck. Did you get any further in your attempts?

My attempt is here: https://github.com/jonaskello/rabbit-web

I have setup docker compose to run both relay and rabbit containers. The code is from the readme file of amqp-client.js but I removed everything after connect.

The error I get in Chrome console is very cryptic (and I don't see any messages in the relay logs):

```
WebSocket connection to 'ws://localhost:15670/' failed:
localhost/:1 Uncaught Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
error (async)
(anonymous) @ amqp-websocket-client.mjs:2017
connect @ amqp-websocket-client.mjs:2014
(anonymous) @ (index):12
```

@carlhoerberg If you could check for any obvious misconfiguration I'm doing in the above example that would be very helpful :-)

**Comment by jonaskello** [comment]
After some more trial and error I actually got it to work :-)

The problem was that by default relay does `--bind 127.0.0.1` but this does not work inside a container that exposes ports. Instead it needs to be `--bind 0.0.0.0`. After I changed that [here](https://github.com/jonaskello/rabbit-web/blob/main/docker-compose.yaml#L6) it started working 🚀

**Comment by arawak** [comment]
@jonaskello I got distracted by Christmas and other projects and kind of forgot about it.

I'll see if I can replicate your success.

**Comment by carlhoerberg** [comment]
Thank you for reporting! Fixed in https://github.com/cloudamqp/websocket-tcp-relay/commit/e96f0403ef40525a98c176a19c4e44aef0b7484e

**Comment by steveb85** [comment]
@carlhoerberg  I found this exact same issue just now with the ubuntu install (non docker) after a few hours of confusion this thread saved me, on a VM that has ports exposed through a firewall, the same thing is required, bind 0.0.0.0 and it started working. perhaps even just a mention on the readme could save others. thanks
