### ISSUE TITLE
Ability to set prefix path for the relay

### ISSUE THREAD

**Issue by harsh04** [cloudamqp/websocket-tcp-relay#11]
I am deploying the docker inside a GKE cluster and I want to link the access to the websocket-tcp-relay container via an ingress on /relay/* path. Now on GKE, it doesn't allow to set prefix. So i was wondering if we can setup the prefix in the container itself.

**Comment by dentarg** [comment]
Can you show what you have in mind with a PR? 

I don't think I follow what you ask (maybe you can provide some more context, any docs links that would explain more?)

**Comment by carlhoerberg** [comment]
The websocket part is path agnostic, it's not using it, so use any path you would like. But the webroot (serving of static files) requires path modification in the code, will fix.
