### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by PHGamer** [cloudamqp/websocket-tcp-relay#17]
is this necessary if one is using nginx with websockets? is there a way to forward straight to rabbitmq or is this converting websocket traffic to AMQP traffic dynamically.  in which case would it be nginx LB -> websocket-tcp-relay-> rabbit?

**Comment by carlhoerberg** [comment]
Nginx cant convert websocket<->TCP afaik

**Comment by dentarg** [comment]
> is this converting websocket traffic to AMQP traffic dynamically. 

Yes

> in which case would it be nginx LB -> websocket-tcp-relay-> rabbit?

Yes
