### ISSUE TITLE
Please tag individual releases in Docker

### ISSUE THREAD

**Issue by ngbrown** [cloudamqp/websocket-tcp-relay#5]
I was using the `1.0.4` [tagged docker release](https://hub.docker.com/r/cloudamqp/websocket-tcp-relay/tags) in Kubernetes because our standard is to use versioned containers. And I got stuck trying to figure out why I kept getting the following error when it was working fine locally (using `latest` tag):

```
x.x.x.x:443 disconnected: #<Socket::ConnectError:Error connecting to 'rabbitmq.default.svc.cluster.local:443': Host is unreachable>
```

I was clearly setting the upstream as `tcp://rabbitmq.default.svc.cluster.local:5672`, so why the port change in the error?

I finally noticed that the `1.0.4` tag is a year old. Switching to `latest` tag works. But what is the version number so I can tag my own copy?

**Comment by dentarg** [comment]
Tagged `v1.0.5`, see https://hub.docker.com/layers/websocket-tcp-relay/cloudamqp/websocket-tcp-relay/v1.0.5/images/sha256-d4f94934edf9f3c91545472d2c266001e1f15ecb19fda8f43a59b736f927c633?context=explore
