### ISSUE TITLE
Invalid PROXY protocol header generated when X-Forwarded-For header contains IPv6 address

### ISSUE THREAD

**Issue by ngbrown** [cloudamqp/websocket-tcp-relay#6]
I am getting an error trying to connect through `websocket-tcp-relay`, but only when connecting over IPv6 with my cell phone (Android 10, with Chrome browser) on mobile data. I only have IPv6 when using exclusively LTE on my cell phone. Enabling WiFi only connects by IPv4, and that works. `websocket-tcp-relay` is upstream from a TLS terminating proxy that passes a `X-Forwarded-For` header. I had the PROXY protocol enabled for all incoming connections on the upstream RabbitMQ instance. The PROXY protocol expects both addresses to be in the same family and RabbitMQ rejects an attempt to use mixed formats.

In the web application, the AMQP WebSocket would try connecting, and then immediately throw an error. The same web application worked fine from the cell phone when connected to WiFi.

I had `--proxy-protocol` passed as a parameter to the websocket relay container, and `proxy_protocol = true` set in the RabbitMQ config. This is with a container pulled at e96f0403ef40525a98c176a19c4e44aef0b7484e, but no code changes have happened in this repo since then.

`websocket-tcp-relay` is not terminating TLS on this connection, that is being done by the ingress controller. The full `args` line in the Kubernetes manifest is:

```
args: ["--port", "15670", "--upstream", "tcp://rabbitmq.default.svc.cluster.local:5672", "--proxy-protocol"]
```

I get the following error from RabbitMQ in debug logging mode:

```
error when receiving proxy header: 'Failed to parse an IPv6 address in the PROXY protocol header line. (PP 2.1)'
```

Meanwhile, the websocket relay has this sequence of log messages:

```
[2600:1011:b015:aaac:xxxx:xxxx:xxxx:xxxx]:443 connected
[2600:1011:b015:aaac:xxxx:xxxx:xxxx:xxxx]:443 connected to upstream
[2600:1011:b015:aaac:xxxx:xxxx:xxxx:xxxx]:443 disconnected: #<IO::Error:Error reading socket: Connection reset by peer>
```

> Note: I masked the last 64 bits of the address, since it's a public address.

I was able to connect the Chrome debugger to my phone, and I see only the first AMQP packet is sent out, and then the WebSocket goes into a `readyState` of `3` (CLOSED) and `@cloudamqp/amqp-client` then throws.

Removing `proxy_protocol = true` in RabbitMQ and restarting websocket relay without `--proxy-protocol` resolved the connection issue, and the phone can now connect over LTE and IPv6.

These are the lines in `websocket-tcp-relay` that generate the PROXY header:

https://github.com/cloudamqp/websocket-tcp-relay/blob/05987b2fcdd283b2b7926150c92482eee30fd45e/src/websocket-tcp-relay/websocket_relay.cr#L25-L29

The container `websocket-tcp-relay` has a local IPv4 address as does RabbitMQ's container. The remote IPv6 address is being read off of the `X-Forwarded-For` header in the incoming HTTP request.

What I suspect is happening, is that the incoming (forwarded) address being IPv6 means that the `TCP6` prefix is written in the PROXY header. Then with the `TCP6` header written, RabbitMQ is expecting all address to be in the IPv6 format. The [PROXY protocol spec](https://www.haproxy.org/download/1.9/doc/proxy-protocol.txt) doesn't seem to be clear in what to do with mixed addresses in this case. It is clear that `TCP6` should only have IPv6 formatted addresses (colons and hex values).

I would suspect the right thing to do would be embed the local IPv4 address into an IPv6 address like described in [RFC4038](https://datatracker.ietf.org/doc/html/rfc4038#section-4.2).

So the local address of `10.252.221.48` could be written as `::ffff:AFC:DD30`. RabbitMQ might also accept a dotted postfix like `::ffff:10.252.221.48` in their Erlang IP address string parser, but I'm not clear if that is canonical or not for the PROXY header.

As an aside, if this code is going to be re-worked, maybe support outputting the binary format with an option?

**Comment by ngbrown** [comment]
Thanks for updating this. I can turn `--proxy-protocol` back on, RabbitMQ is happy, and the management interface shows the IPv6 address as desired.

![Screenshot (10)](https://user-images.githubusercontent.com/228987/182489331-8d0290b1-c0a5-4b8e-90ce-b268554f38d1.png)

**Comment by carlhoerberg** [comment]
Cool! Thank you for confirming!
