### ISSUE TITLE
Handle SIGTERM in process and to exit immediately

### ISSUE THREAD

**Issue by ngbrown** [cloudamqp/websocket-tcp-relay#7]
It currently takes 10 seconds before Docker force kills the container on stop. See the [Docker FAQ](https://docs.docker.com/compose/faq/#:~:text=startup%20order.-,Why%20do%20my%20services%20take%2010%20seconds%20to%20recreate%20or%20stop%3F).

If this process can handle the SIGTERM signal directly, or include something like [dumb-init](https://github.com/Yelp/dumb-init), then the process can exit on demand and then docker doesn't have to force kill the container.

**Comment by carlhoerberg** [comment]
Yes, will take a look when I'm back from vacation in august.
